# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FOOD_DEV.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 700)
        MainWindow.setStyleSheet("background-color: rgb(31, 80, 20);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_container = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_container.sizePolicy().hasHeightForWidth())
        self.left_container.setSizePolicy(sizePolicy)
        self.left_container.setMinimumSize(QtCore.QSize(300, 0))
        self.left_container.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.left_container.setFont(font)
        self.left_container.setStyleSheet("background-color: rgb(246, 246, 233);")
        self.left_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_container.setObjectName("left_container")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.left_container)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.left_container)
        self.stackedWidget.setObjectName("stackedWidget")
        self.lateral_menu = QtWidgets.QWidget()
        self.lateral_menu.setObjectName("lateral_menu")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.lateral_menu)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_12.addItem(spacerItem)
        self.menu_title = QtWidgets.QLabel(self.lateral_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_title.sizePolicy().hasHeightForWidth())
        self.menu_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(20)
        self.menu_title.setFont(font)
        self.menu_title.setAlignment(QtCore.Qt.AlignCenter)
        self.menu_title.setObjectName("menu_title")
        self.verticalLayout_12.addWidget(self.menu_title)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_12.addItem(spacerItem1)
        self.btn_client = QtWidgets.QPushButton(self.lateral_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_client.sizePolicy().hasHeightForWidth())
        self.btn_client.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Sans Medium")
        font.setPointSize(24)
        self.btn_client.setFont(font)
        self.btn_client.setAutoFillBackground(False)
        self.btn_client.setStyleSheet("QPushButton:hover\n"
"{\n"
"   border: 4px solid  rgb(31, 80, 20);\n"
"    background-color: rgb(236, 236, 224);\n"
"}\n"
"")
        self.btn_client.setAutoDefault(False)
        self.btn_client.setDefault(False)
        self.btn_client.setFlat(True)
        self.btn_client.setObjectName("btn_client")
        self.verticalLayout_12.addWidget(self.btn_client)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_12.addItem(spacerItem2)
        self.btn_product = QtWidgets.QPushButton(self.lateral_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_product.sizePolicy().hasHeightForWidth())
        self.btn_product.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Sans Medium")
        font.setPointSize(24)
        self.btn_product.setFont(font)
        self.btn_product.setStyleSheet("QPushButton:hover\n"
"{\n"
"   border: 4px solid  rgb(31, 80, 20);\n"
"    background-color: rgb(236, 236, 224);\n"
"\n"
"}\n"
"")
        self.btn_product.setAutoDefault(False)
        self.btn_product.setFlat(True)
        self.btn_product.setObjectName("btn_product")
        self.verticalLayout_12.addWidget(self.btn_product)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_12.addItem(spacerItem3)
        self.btn_order = QtWidgets.QPushButton(self.lateral_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_order.sizePolicy().hasHeightForWidth())
        self.btn_order.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Sans Medium")
        font.setPointSize(24)
        self.btn_order.setFont(font)
        self.btn_order.setToolTip("")
        self.btn_order.setStyleSheet("QPushButton:hover\n"
"{\n"
"   border: 4px solid  rgb(31, 80, 20);\n"
"    background-color: rgb(236, 236, 224);\n"
"\n"
"}\n"
"")
        self.btn_order.setAutoDefault(False)
        self.btn_order.setFlat(True)
        self.btn_order.setObjectName("btn_order")
        self.verticalLayout_12.addWidget(self.btn_order)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_12.addItem(spacerItem4)
        self.btn_about = QtWidgets.QPushButton(self.lateral_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_about.sizePolicy().hasHeightForWidth())
        self.btn_about.setSizePolicy(sizePolicy)
        self.btn_about.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_about.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Fira Sans Medium")
        font.setPointSize(20)
        self.btn_about.setFont(font)
        self.btn_about.setStyleSheet("QPushButton:hover\n"
"{\n"
"   border: 4px solid  rgb(31, 80, 20);\n"
"    background-color: rgb(236, 236, 224);\n"
"\n"
"}\n"
"")
        self.btn_about.setAutoDefault(False)
        self.btn_about.setFlat(True)
        self.btn_about.setObjectName("btn_about")
        self.verticalLayout_12.addWidget(self.btn_about)
        spacerItem5 = QtWidgets.QSpacerItem(50, 180, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_12.addItem(spacerItem5)
        self.stackedWidget.addWidget(self.lateral_menu)
        self.client_menu = QtWidgets.QWidget()
        self.client_menu.setObjectName("client_menu")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.client_menu)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_4.addItem(spacerItem6)
        self.client_title = QtWidgets.QLabel(self.client_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.client_title.sizePolicy().hasHeightForWidth())
        self.client_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(20)
        self.client_title.setFont(font)
        self.client_title.setAlignment(QtCore.Qt.AlignCenter)
        self.client_title.setObjectName("client_title")
        self.verticalLayout_4.addWidget(self.client_title)
        spacerItem7 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_4.addItem(spacerItem7)
        self.btn_regiter_client = QtWidgets.QPushButton(self.client_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_regiter_client.sizePolicy().hasHeightForWidth())
        self.btn_regiter_client.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Sans Medium")
        font.setPointSize(24)
        self.btn_regiter_client.setFont(font)
        self.btn_regiter_client.setStyleSheet("QPushButton:hover\n"
"{\n"
"   border: 4px solid  rgb(31, 80, 20);\n"
"    background-color: rgb(236, 236, 224);\n"
"\n"
"}\n"
"")
        self.btn_regiter_client.setFlat(True)
        self.btn_regiter_client.setObjectName("btn_regiter_client")
        self.verticalLayout_4.addWidget(self.btn_regiter_client)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_4.addItem(spacerItem8)
        self.btn_records_client = QtWidgets.QPushButton(self.client_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_records_client.sizePolicy().hasHeightForWidth())
        self.btn_records_client.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Sans Medium")
        font.setPointSize(20)
        self.btn_records_client.setFont(font)
        self.btn_records_client.setStyleSheet("QPushButton:hover\n"
"{\n"
"   border: 4px solid  rgb(31, 80, 20);\n"
"    background-color: rgb(236, 236, 224);\n"
"\n"
"}\n"
"")
        self.btn_records_client.setFlat(True)
        self.btn_records_client.setObjectName("btn_records_client")
        self.verticalLayout_4.addWidget(self.btn_records_client)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_4.addItem(spacerItem9)
        self.btn_update_client = QtWidgets.QPushButton(self.client_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_update_client.sizePolicy().hasHeightForWidth())
        self.btn_update_client.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Sans Medium")
        font.setPointSize(24)
        self.btn_update_client.setFont(font)
        self.btn_update_client.setStyleSheet("QPushButton:hover\n"
"{\n"
"   border: 4px solid  rgb(31, 80, 20);\n"
"    background-color: rgb(236, 236, 224);\n"
"\n"
"}\n"
"")
        self.btn_update_client.setFlat(True)
        self.btn_update_client.setObjectName("btn_update_client")
        self.verticalLayout_4.addWidget(self.btn_update_client)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_4.addItem(spacerItem10)
        self.btn_delete_client = QtWidgets.QPushButton(self.client_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_delete_client.sizePolicy().hasHeightForWidth())
        self.btn_delete_client.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Sans Medium")
        font.setPointSize(24)
        self.btn_delete_client.setFont(font)
        self.btn_delete_client.setStyleSheet("QPushButton:hover\n"
"{\n"
"   border: 4px solid  rgb(31, 80, 20);\n"
"    background-color: rgb(236, 236, 224);\n"
"\n"
"}\n"
"")
        self.btn_delete_client.setFlat(True)
        self.btn_delete_client.setObjectName("btn_delete_client")
        self.verticalLayout_4.addWidget(self.btn_delete_client)
        spacerItem11 = QtWidgets.QSpacerItem(20, 180, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_4.addItem(spacerItem11)
        self.btn_back_client = QtWidgets.QPushButton(self.client_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back_client.sizePolicy().hasHeightForWidth())
        self.btn_back_client.setSizePolicy(sizePolicy)
        self.btn_back_client.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_back_client.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Fira Sans Medium")
        font.setPointSize(20)
        self.btn_back_client.setFont(font)
        self.btn_back_client.setStyleSheet("QPushButton:hover\n"
"{\n"
"   border: 4px solid  rgb(31, 80, 20);\n"
"    background-color: rgb(236, 236, 224);\n"
"\n"
"}\n"
"")
        self.btn_back_client.setAutoDefault(False)
        self.btn_back_client.setFlat(True)
        self.btn_back_client.setObjectName("btn_back_client")
        self.verticalLayout_4.addWidget(self.btn_back_client)
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_4.addItem(spacerItem12)
        self.stackedWidget.addWidget(self.client_menu)
        self.product_menu = QtWidgets.QWidget()
        self.product_menu.setObjectName("product_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.product_menu)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem13 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem13)
        self.product_title = QtWidgets.QLabel(self.product_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product_title.sizePolicy().hasHeightForWidth())
        self.product_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(20)
        self.product_title.setFont(font)
        self.product_title.setTextFormat(QtCore.Qt.AutoText)
        self.product_title.setAlignment(QtCore.Qt.AlignCenter)
        self.product_title.setObjectName("product_title")
        self.verticalLayout_2.addWidget(self.product_title)
        spacerItem14 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem14)
        self.btn_insert_prod = QtWidgets.QPushButton(self.product_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_insert_prod.sizePolicy().hasHeightForWidth())
        self.btn_insert_prod.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Sans Medium")
        font.setPointSize(24)
        self.btn_insert_prod.setFont(font)
        self.btn_insert_prod.setStyleSheet("QPushButton:hover\n"
"{\n"
"   border: 4px solid  rgb(31, 80, 20);\n"
"    background-color: rgb(236, 236, 224);\n"
"\n"
"}\n"
"")
        self.btn_insert_prod.setFlat(True)
        self.btn_insert_prod.setObjectName("btn_insert_prod")
        self.verticalLayout_2.addWidget(self.btn_insert_prod)
        spacerItem15 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem15)
        self.btn_stock_prod = QtWidgets.QPushButton(self.product_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_stock_prod.sizePolicy().hasHeightForWidth())
        self.btn_stock_prod.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Sans Medium")
        font.setPointSize(24)
        self.btn_stock_prod.setFont(font)
        self.btn_stock_prod.setStyleSheet("QPushButton:hover\n"
"{\n"
"   border: 4px solid  rgb(31, 80, 20);\n"
"    background-color: rgb(236, 236, 224);\n"
"\n"
"}\n"
"")
        self.btn_stock_prod.setFlat(True)
        self.btn_stock_prod.setObjectName("btn_stock_prod")
        self.verticalLayout_2.addWidget(self.btn_stock_prod)
        spacerItem16 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem16)
        self.btn_update_prod = QtWidgets.QPushButton(self.product_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_update_prod.sizePolicy().hasHeightForWidth())
        self.btn_update_prod.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Sans Medium")
        font.setPointSize(24)
        self.btn_update_prod.setFont(font)
        self.btn_update_prod.setStyleSheet("QPushButton:hover\n"
"{\n"
"   border: 4px solid  rgb(31, 80, 20);\n"
"    background-color: rgb(236, 236, 224);\n"
"\n"
"}\n"
"")
        self.btn_update_prod.setFlat(True)
        self.btn_update_prod.setObjectName("btn_update_prod")
        self.verticalLayout_2.addWidget(self.btn_update_prod)
        spacerItem17 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem17)
        self.btn_delete_prod = QtWidgets.QPushButton(self.product_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_delete_prod.sizePolicy().hasHeightForWidth())
        self.btn_delete_prod.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Sans Medium")
        font.setPointSize(24)
        self.btn_delete_prod.setFont(font)
        self.btn_delete_prod.setStyleSheet("QPushButton:hover\n"
"{\n"
"   border: 4px solid  rgb(31, 80, 20);\n"
"    background-color: rgb(236, 236, 224);\n"
"\n"
"}\n"
"")
        self.btn_delete_prod.setFlat(True)
        self.btn_delete_prod.setObjectName("btn_delete_prod")
        self.verticalLayout_2.addWidget(self.btn_delete_prod)
        spacerItem18 = QtWidgets.QSpacerItem(20, 180, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem18)
        self.btn_back_product = QtWidgets.QPushButton(self.product_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back_product.sizePolicy().hasHeightForWidth())
        self.btn_back_product.setSizePolicy(sizePolicy)
        self.btn_back_product.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_back_product.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Fira Sans Medium")
        font.setPointSize(20)
        self.btn_back_product.setFont(font)
        self.btn_back_product.setStyleSheet("QPushButton:hover\n"
"{\n"
"   border: 4px solid  rgb(31, 80, 20);\n"
"    background-color: rgb(236, 236, 224);\n"
"\n"
"}\n"
"")
        self.btn_back_product.setAutoDefault(False)
        self.btn_back_product.setFlat(True)
        self.btn_back_product.setObjectName("btn_back_product")
        self.verticalLayout_2.addWidget(self.btn_back_product)
        spacerItem19 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem19)
        self.stackedWidget.addWidget(self.product_menu)
        self.order_menu = QtWidgets.QWidget()
        self.order_menu.setObjectName("order_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.order_menu)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem20 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem20)
        self.order_title = QtWidgets.QLabel(self.order_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.order_title.sizePolicy().hasHeightForWidth())
        self.order_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setPointSize(20)
        self.order_title.setFont(font)
        self.order_title.setAlignment(QtCore.Qt.AlignCenter)
        self.order_title.setObjectName("order_title")
        self.verticalLayout_3.addWidget(self.order_title)
        spacerItem21 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem21)
        self.btn_do_order = QtWidgets.QPushButton(self.order_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_do_order.sizePolicy().hasHeightForWidth())
        self.btn_do_order.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Sans Medium")
        font.setPointSize(24)
        self.btn_do_order.setFont(font)
        self.btn_do_order.setStyleSheet("QPushButton:hover\n"
"{\n"
"   border: 4px solid  rgb(31, 80, 20);\n"
"    background-color: rgb(236, 236, 224);\n"
"\n"
"}\n"
"")
        self.btn_do_order.setFlat(True)
        self.btn_do_order.setObjectName("btn_do_order")
        self.verticalLayout_3.addWidget(self.btn_do_order)
        spacerItem22 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem22)
        self.btn_records_order = QtWidgets.QPushButton(self.order_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_records_order.sizePolicy().hasHeightForWidth())
        self.btn_records_order.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Sans Medium")
        font.setPointSize(20)
        self.btn_records_order.setFont(font)
        self.btn_records_order.setStyleSheet("QPushButton:hover\n"
"{\n"
"   border: 4px solid  rgb(31, 80, 20);\n"
"    background-color: rgb(236, 236, 224);\n"
"\n"
"}\n"
"")
        self.btn_records_order.setFlat(True)
        self.btn_records_order.setObjectName("btn_records_order")
        self.verticalLayout_3.addWidget(self.btn_records_order)
        spacerItem23 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem23)
        self.btn_update_order = QtWidgets.QPushButton(self.order_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_update_order.sizePolicy().hasHeightForWidth())
        self.btn_update_order.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Sans Medium")
        font.setPointSize(24)
        self.btn_update_order.setFont(font)
        self.btn_update_order.setStyleSheet("QPushButton:hover\n"
"{\n"
"   border: 4px solid  rgb(31, 80, 20);\n"
"    background-color: rgb(236, 236, 224);\n"
"\n"
"}\n"
"")
        self.btn_update_order.setFlat(True)
        self.btn_update_order.setObjectName("btn_update_order")
        self.verticalLayout_3.addWidget(self.btn_update_order)
        spacerItem24 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem24)
        self.btn_delete_order = QtWidgets.QPushButton(self.order_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_delete_order.sizePolicy().hasHeightForWidth())
        self.btn_delete_order.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Sans Medium")
        font.setPointSize(24)
        self.btn_delete_order.setFont(font)
        self.btn_delete_order.setStyleSheet("QPushButton:hover\n"
"{\n"
"   border: 4px solid  rgb(31, 80, 20);\n"
"    background-color: rgb(236, 236, 224);\n"
"\n"
"}\n"
"")
        self.btn_delete_order.setFlat(True)
        self.btn_delete_order.setObjectName("btn_delete_order")
        self.verticalLayout_3.addWidget(self.btn_delete_order)
        spacerItem25 = QtWidgets.QSpacerItem(20, 180, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem25)
        self.btn_back_order = QtWidgets.QPushButton(self.order_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back_order.sizePolicy().hasHeightForWidth())
        self.btn_back_order.setSizePolicy(sizePolicy)
        self.btn_back_order.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_back_order.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Fira Sans Medium")
        font.setPointSize(20)
        self.btn_back_order.setFont(font)
        self.btn_back_order.setStyleSheet("QPushButton:hover\n"
"{\n"
"   border: 4px solid  rgb(31, 80, 20);\n"
"    background-color: rgb(236, 236, 224);\n"
"\n"
"}\n"
"")
        self.btn_back_order.setAutoDefault(False)
        self.btn_back_order.setFlat(True)
        self.btn_back_order.setObjectName("btn_back_order")
        self.verticalLayout_3.addWidget(self.btn_back_order)
        spacerItem26 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem26)
        self.stackedWidget.addWidget(self.order_menu)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.left_container)
        self.right_container = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_container.sizePolicy().hasHeightForWidth())
        self.right_container.setSizePolicy(sizePolicy)
        self.right_container.setMinimumSize(QtCore.QSize(650, 650))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.right_container.setFont(font)
        self.right_container.setStyleSheet("background-color: rgb(125, 155, 118);")
        self.right_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_container.setObjectName("right_container")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.right_container)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.right_container)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_logo = QtWidgets.QWidget()
        self.page_logo.setStyleSheet("")
        self.page_logo.setObjectName("page_logo")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_logo)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.FOOD_DEV_logo = QtWidgets.QLabel(self.page_logo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FOOD_DEV_logo.sizePolicy().hasHeightForWidth())
        self.FOOD_DEV_logo.setSizePolicy(sizePolicy)
        self.FOOD_DEV_logo.setMinimumSize(QtCore.QSize(0, 300))
        self.FOOD_DEV_logo.setMaximumSize(QtCore.QSize(16777211, 16777215))
        self.FOOD_DEV_logo.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Voga")
        font.setPointSize(118)
        self.FOOD_DEV_logo.setFont(font)
        self.FOOD_DEV_logo.setTextFormat(QtCore.Qt.AutoText)
        self.FOOD_DEV_logo.setScaledContents(False)
        self.FOOD_DEV_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.FOOD_DEV_logo.setIndent(-1)
        self.FOOD_DEV_logo.setObjectName("FOOD_DEV_logo")
        self.verticalLayout_5.addWidget(self.FOOD_DEV_logo)
        self.logo = QtWidgets.QFrame(self.page_logo)
        self.logo.setSizeIncrement(QtCore.QSize(0, 0))
        self.logo.setStyleSheet("")
        self.logo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo.setObjectName("logo")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.logo)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.logo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.logo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(400, 300))
        self.frame_3.setStyleSheet("/*background: url(:/LOGO/FOOD_DEV LOGO 2.png) no-repeat center;*/\n"
"border-image: url(:/food/FOOD_DEV LOGO 2.png) 0 0 0 0 stretch stretch;\n"
"/*background-repeat: no-repeat;*/")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.logo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.verticalLayout_5.addWidget(self.logo)
        self.stackedWidget_2.addWidget(self.page_logo)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.title_client = QtWidgets.QFrame(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_client.sizePolicy().hasHeightForWidth())
        self.title_client.setSizePolicy(sizePolicy)
        self.title_client.setMinimumSize(QtCore.QSize(0, 100))
        self.title_client.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_client.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_client.setObjectName("title_client")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.title_client)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.register_sytem = QtWidgets.QLabel(self.title_client)
        font = QtGui.QFont()
        font.setFamily("Voga")
        font.setPointSize(48)
        self.register_sytem.setFont(font)
        self.register_sytem.setAlignment(QtCore.Qt.AlignCenter)
        self.register_sytem.setObjectName("register_sytem")
        self.verticalLayout_7.addWidget(self.register_sytem)
        self.enter_data = QtWidgets.QLabel(self.title_client)
        font = QtGui.QFont()
        font.setFamily("Fira Sans Medium")
        font.setPointSize(28)
        self.enter_data.setFont(font)
        self.enter_data.setAlignment(QtCore.Qt.AlignCenter)
        self.enter_data.setObjectName("enter_data")
        self.verticalLayout_7.addWidget(self.enter_data)
        self.cadastro_basic_client = QtWidgets.QFrame(self.title_client)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cadastro_basic_client.sizePolicy().hasHeightForWidth())
        self.cadastro_basic_client.setSizePolicy(sizePolicy)
        self.cadastro_basic_client.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cadastro_basic_client.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cadastro_basic_client.setObjectName("cadastro_basic_client")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.cadastro_basic_client)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame = QtWidgets.QFrame(self.cadastro_basic_client)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Voga")
        font.setPointSize(20)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("QLineEdit:focus, QLineEdit:hover\n"
"{\n"
"    \n"
"    background-color: rgb(255, 219, 187);\n"
"}\n"
"QLineEdit\n"
"{\n"
"    background-color: rgb(246, 246, 233);\n"
"}")
        self.lineEdit_6.setInputMask("")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_5.addWidget(self.lineEdit_6)
        self.verticalLayout_8.addWidget(self.frame)
        self.frame_6 = QtWidgets.QFrame(self.cadastro_basic_client)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Voga")
        font.setPointSize(20)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("QLineEdit:focus, QLineEdit:hover\n"
"{\n"
"    \n"
"    background-color: rgb(255, 219, 187);\n"
"}\n"
"QLineEdit\n"
"{\n"
"    background-color: rgb(246, 246, 233);\n"
"}")
        self.lineEdit_7.setInputMask("")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_6.addWidget(self.lineEdit_7)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem27)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_8.setSizePolicy(sizePolicy)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Voga")
        font.setPointSize(20)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("QLineEdit:focus, QLineEdit:hover\n"
"{\n"
"    \n"
"    background-color: rgb(255, 219, 187);\n"
"}\n"
"QLineEdit\n"
"{\n"
"    background-color: rgb(246, 246, 233);\n"
"}")
        self.lineEdit_8.setInputMask("")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_6.addWidget(self.lineEdit_8)
        self.verticalLayout_8.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.cadastro_basic_client)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Voga")
        font.setPointSize(20)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet("QLineEdit:focus, QLineEdit:hover\n"
"{\n"
"    \n"
"    background-color: rgb(255, 219, 187);\n"
"}\n"
"QLineEdit\n"
"{\n"
"    background-color: rgb(246, 246, 233);\n"
"}")
        self.lineEdit_9.setInputMask("")
        self.lineEdit_9.setText("")
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_7.addWidget(self.lineEdit_9)
        self.verticalLayout_8.addWidget(self.frame_7)
        self.frame_9 = QtWidgets.QFrame(self.cadastro_basic_client)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Voga")
        font.setPointSize(20)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setStyleSheet("QLineEdit:focus, QLineEdit:hover\n"
"{\n"
"    \n"
"    background-color: rgb(255, 219, 187);\n"
"}\n"
"QLineEdit\n"
"{\n"
"    background-color: rgb(246, 246, 233);\n"
"}")
        self.lineEdit_11.setInputMask("")
        self.lineEdit_11.setText("")
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_8.addWidget(self.lineEdit_11)
        self.verticalLayout_8.addWidget(self.frame_9)
        self.frame_8 = QtWidgets.QFrame(self.cadastro_basic_client)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_12.sizePolicy().hasHeightForWidth())
        self.lineEdit_12.setSizePolicy(sizePolicy)
        self.lineEdit_12.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Voga")
        font.setPointSize(20)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setStyleSheet("QLineEdit:focus, QLineEdit:hover\n"
"{\n"
"    \n"
"    background-color: rgb(255, 219, 187);\n"
"}\n"
"QLineEdit\n"
"{\n"
"    background-color: rgb(246, 246, 233);\n"
"}")
        self.lineEdit_12.setInputMask("")
        self.lineEdit_12.setText("")
        self.lineEdit_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_9.addWidget(self.lineEdit_12)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem28)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_10.sizePolicy().hasHeightForWidth())
        self.lineEdit_10.setSizePolicy(sizePolicy)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Voga")
        font.setPointSize(20)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setStyleSheet("QLineEdit:focus, QLineEdit:hover\n"
"{\n"
"    \n"
"    background-color: rgb(255, 219, 187);\n"
"}\n"
"QLineEdit\n"
"{\n"
"    background-color: rgb(246, 246, 233);\n"
"}")
        self.lineEdit_10.setInputMask("")
        self.lineEdit_10.setText("")
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_9.addWidget(self.lineEdit_10)
        self.verticalLayout_8.addWidget(self.frame_8)
        self.verticalLayout_7.addWidget(self.cadastro_basic_client)
        self.verticalLayout_6.addWidget(self.title_client)
        self.buttons = QtWidgets.QFrame(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttons.sizePolicy().hasHeightForWidth())
        self.buttons.setSizePolicy(sizePolicy)
        self.buttons.setMinimumSize(QtCore.QSize(0, 100))
        self.buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons.setObjectName("buttons")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.buttons)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_back_client_reg = QtWidgets.QPushButton(self.buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back_client_reg.sizePolicy().hasHeightForWidth())
        self.btn_back_client_reg.setSizePolicy(sizePolicy)
        self.btn_back_client_reg.setMinimumSize(QtCore.QSize(200, 0))
        self.btn_back_client_reg.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Fira Sans Medium")
        font.setPointSize(20)
        self.btn_back_client_reg.setFont(font)
        self.btn_back_client_reg.setAutoFillBackground(False)
        self.btn_back_client_reg.setStyleSheet("QPushButton:hover\n"
"{\n"
"   border: 4px solid  rgb(31, 80, 20);\n"
"    background-color: rgb(212, 212, 201);\n"
"    \n"
"\n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(236, 236, 224);\n"
"    border: none;\n"
"}\n"
"")
        self.btn_back_client_reg.setAutoDefault(False)
        self.btn_back_client_reg.setDefault(False)
        self.btn_back_client_reg.setFlat(False)
        self.btn_back_client_reg.setObjectName("btn_back_client_reg")
        self.horizontalLayout_4.addWidget(self.btn_back_client_reg)
        spacerItem29 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem29)
        self.btn_next_client_reg = QtWidgets.QPushButton(self.buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_next_client_reg.sizePolicy().hasHeightForWidth())
        self.btn_next_client_reg.setSizePolicy(sizePolicy)
        self.btn_next_client_reg.setMinimumSize(QtCore.QSize(200, 0))
        self.btn_next_client_reg.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Fira Sans Medium")
        font.setPointSize(20)
        self.btn_next_client_reg.setFont(font)
        self.btn_next_client_reg.setStyleSheet("QPushButton:hover\n"
"{\n"
"   border: 4px solid  rgb(31, 80, 20);\n"
"    background-color: rgb(212, 212, 201);\n"
"    \n"
"\n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(236, 236, 224);\n"
"    border: none;\n"
"}\n"
"")
        self.btn_next_client_reg.setAutoDefault(False)
        self.btn_next_client_reg.setFlat(False)
        self.btn_next_client_reg.setObjectName("btn_next_client_reg")
        self.horizontalLayout_4.addWidget(self.btn_next_client_reg)
        self.verticalLayout_6.addWidget(self.buttons)
        self.stackedWidget_2.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget_2)
        self.horizontalLayout.addWidget(self.right_container)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_title.setText(_translate("MainWindow", "LATERAL MENU"))
        self.btn_client.setText(_translate("MainWindow", "CLIENT"))
        self.btn_product.setText(_translate("MainWindow", "PRODUCT"))
        self.btn_order.setText(_translate("MainWindow", "ORDER"))
        self.btn_about.setText(_translate("MainWindow", "ABOUT SYSTEM"))
        self.client_title.setText(_translate("MainWindow", "CLIENT"))
        self.btn_regiter_client.setText(_translate("MainWindow", "REGISTER"))
        self.btn_records_client.setText(_translate("MainWindow", "VIEW RECORDS"))
        self.btn_update_client.setText(_translate("MainWindow", "UPDATE"))
        self.btn_delete_client.setText(_translate("MainWindow", "DELETE"))
        self.btn_back_client.setText(_translate("MainWindow", "MAIN MENU"))
        self.product_title.setText(_translate("MainWindow", "PRODUCT"))
        self.btn_insert_prod.setText(_translate("MainWindow", "INSERT"))
        self.btn_stock_prod.setText(_translate("MainWindow", "STOCK"))
        self.btn_update_prod.setText(_translate("MainWindow", "UPDATE"))
        self.btn_delete_prod.setText(_translate("MainWindow", "DELETE"))
        self.btn_back_product.setText(_translate("MainWindow", "MAIN MENU"))
        self.order_title.setText(_translate("MainWindow", "ORDER"))
        self.btn_do_order.setText(_translate("MainWindow", "DO ORDER"))
        self.btn_records_order.setText(_translate("MainWindow", "VIEW RECORDS"))
        self.btn_update_order.setText(_translate("MainWindow", "UPDATE"))
        self.btn_delete_order.setText(_translate("MainWindow", "DELETE"))
        self.btn_back_order.setText(_translate("MainWindow", "MAIN MENU"))
        self.FOOD_DEV_logo.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#f6f6e9;\">FOOD_DEV</span></p></body></html>"))
        self.register_sytem.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#f6f6e9;\">REGISTER SYSTEM</span></p></body></html>"))
        self.enter_data.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#f6f6e9;\">ENTER THE DATA</span></p></body></html>"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "Name"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "CPF"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "PHONE NUMBER"))
        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "EMAIL"))
        self.lineEdit_11.setPlaceholderText(_translate("MainWindow", "CARD NUMBER"))
        self.lineEdit_12.setPlaceholderText(_translate("MainWindow", "CVV"))
        self.lineEdit_10.setPlaceholderText(_translate("MainWindow", "Expiration Date"))
        self.btn_back_client_reg.setText(_translate("MainWindow", "BACK"))
        self.btn_next_client_reg.setText(_translate("MainWindow", "NEXT"))
import logo


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
