# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Alert_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from utils.INTERFACE_FUNCIONALITIES import fonte_rc, logo_rc

class Ui_Alert_win(object):
    def setupUi(self, MainWindow):
        QtGui.QFontDatabase.addApplicationFont(":/fonte/Interface_files/FiraSans-Medium.ttf")
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 300)
        MainWindow.setMinimumSize(QtCore.QSize(350, 300))
        MainWindow.setMaximumSize(QtCore.QSize(350, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(350, 300))
        self.centralwidget.setMaximumSize(QtCore.QSize(350, 300))
        self.centralwidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 158, 94, 255), stop:1 rgba(255, 115, 75,255));\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Alert_win_f1 = QtWidgets.QFrame(self.centralwidget)
        self.Alert_win_f1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Alert_win_f1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Alert_win_f1.setObjectName("Alert_win_f1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Alert_win_f1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Alert_win_f1_lb = QtWidgets.QLabel(self.Alert_win_f1)
        self.Alert_win_f1_lb.setStyleSheet("font: 20pt \"Voga \"; color:#f6f6e9;")
        self.Alert_win_f1_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.Alert_win_f1_lb.setObjectName("Alert_win_f1_lb")
        self.horizontalLayout_2.addWidget(self.Alert_win_f1_lb)
        self.verticalLayout.addWidget(self.Alert_win_f1)
        self.Alert_win_f2 = QtWidgets.QFrame(self.centralwidget)
        self.Alert_win_f2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.Alert_win_f2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Alert_win_f2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Alert_win_f2.setObjectName("Alert_win_f2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Alert_win_f2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Alert_win_f1_btn = QtWidgets.QPushButton(self.Alert_win_f2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Alert_win_f1_btn.sizePolicy().hasHeightForWidth())
        self.Alert_win_f1_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Fira Sans Medium")
        font.setPointSize(18)
        self.Alert_win_f1_btn.setFont(font)
        self.Alert_win_f1_btn.setStyleSheet("QPushButton:hover\n"
"{\n"
"   border: 4px solid  rgb(31, 80, 20);\n"
"    background-color: rgb(212, 212, 201);\n"
"    \n"
"\n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(236, 236, 224);\n"
"    border: none;\n"
"}\n"
"")
        self.Alert_win_f1_btn.setObjectName("Alert_win_f1_btn")
        self.horizontalLayout.addWidget(self.Alert_win_f1_btn)
        self.verticalLayout.addWidget(self.Alert_win_f2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Alert_win_f1_lb.setText(_translate("MainWindow", "The field you are trying to fill in, \n"
"accept only text as input"))
        self.Alert_win_f1_btn.setText(_translate("MainWindow", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Alert_win()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
